T130 in vision refactoring
IMSY-DKFZ/simpa pull request #155
Opened 2022-06-27 10:58 UTC by jgroehl

2022-06-27 11:04 UTC, jgroehl commented
This pull request changes:

1. The detector positions of the InVision detection geometry such that they exactly match the positions in the iThera proprietary data files.
2. The efficiency with which optical simulations with multiple illuminations are run. The mcx binary output files are only written once.

2022-07-01 09:44 UTC, kdreher requested changes
Just two minor changes and one question, otherwise it looks good :)

2022-07-01 09:44 UTC, kdreher commented on simpa/core/device_digital_twins/detection_geometries/ithera_invision_array.py
> +        if global_settings[Tags.DIM_VOLUME_Z_MM] < (self.probe_height_mm + 1):
Here we would add 1mm on both sides independently of the spacing. Better change this to one voxel

2022-07-01 09:44 UTC, kdreher commented on simpa/core/device_digital_twins/detection_geometries/ithera_invision_array.py
> +        if global_settings[Tags.DIM_VOLUME_X_MM] < (self.probe_width_mm + 1):
see above

2022-07-01 09:44 UTC, kdreher commented on simpa/core/device_digital_twins/detection_geometries/ithera_invision_array.py
> +        self.positions = (np.asarray([[0.02890019, -0.02837304, 0.],
Would it be possible to calculate these positions based on some basic parameters or do you specifically want these positions and we are allowed by the vendor to publish these positions?

2024-06-22 10:21 UTC, closed without merging