Citation of SIMPA paper
IMSY-DKFZ/simpa pull request #167
Opened 2022-08-17 11:58 UTC by TomTomRixRix

Fixes #124 by adding a citation file and a citation section in the Readme

2022-08-17 12:02 UTC, Holzwarth69126 commented on CITATION.cff
> +  doi: "0.1117/1.JBO.27.8.083010"
DOI wrong - add a 1

2022-08-17 12:03 UTC, Holzwarth69126 commented on README.md
> +Gröhl, Janek, Kris K. Dreher, Melanie Schellenberg, Tom Rix, Niklas Holzwarth, Patricia Vieten, Leonardo Ayala, Sarah E. Bohndiek, Alexander Seitel, and Lena Maier-Hein. *"SIMPA: an open-source toolk
Delete 083010?

2022-08-17 12:04 UTC, Holzwarth69126 requested changes
Please update

2022-08-17 12:10 UTC, Holzwarth69126 approved these changes
Works 🥝

2022-08-18 12:58 UTC, kdreher approved these changes
looks good to me

2022-08-18 12:58 UTC, merged