T9 additional flags
IMSY-DKFZ/simpa pull request #168
Opened 2022-08-17 14:26 UTC by seitela

This pull request adds the possibility to define additional flags for MCX adapter.

2022-08-18 12:54 UTC, kdreher requested changes
I would expect this to be more general for all of the simulation modules:

- [ ] Have "get_additional_flags" as method in the base `SimulationModule` class
- [x] look for to in component settings instead of global settings
- [x] call the Tag "ADDITIONAL_FLAGS"

2022-08-18 12:54 UTC, kdreher commented on simpa/core/simulation_modules/optical_simulation_module/__init__.py
> +            for flag in self.global_settings.get(Tags.MCX_ADDITIONAL_FLAGS[0]):
We usually use `in self.component_settings[Tags.ADDITIONAL_FLAGS]` since the settings class takes care of indexing the first element of the tuple

2022-08-18 12:54 UTC, kdreher commented on simpa/utils/tags.py
> +    MCX_ADDITIONAL_FLAGS = ("mcx_additional_flags", Iterable)
ADDITIONAL_FLAGS (see general remarks)

2022-08-18 12:54 UTC, kdreher commented on simpa_tests/automatic_tests/test_adapters_additional_mcx_flags.py
> +class TestAdditionalFlagsMCXReflectanceAdapter(unittest.TestCase):
This test looks good, I would add a general test case for the `SimulationModule` base class

2024-06-25 09:48 UTC, TomTomRixRix commented
In order to load the `component_settings` in the `SimulationModule` we created an abstract method `get_component_settings` that needs to be implemented in the component base classes, e.g. `OpticalForwardModuleBase`, by simply loading the corresponding component settings, e.g. `self.global_settings.get_optical_settings()`.

2024-06-26 12:15 UTC, TomTomRixRix commented
Closing this PR as it is superseded by #311

2024-06-26 12:15 UTC, closed without merging