T152 processing unit
IMSY-DKFZ/simpa pull request #169
Opened 2022-08-17 14:30 UTC by TomTomRixRix

Fixes issue #152 by implementing a global utility function that determines whether a GPU or CPU is used for processing depending on the user choice and availability of a GPU. 

By default use GPU for fast computation, unless the user manually sets it to CPU. Of course, GPU is only used if available. The user receives a warning if GPU was specified but is not available, in this case processing is done on CPU as fall-back.

This function can then also be used for issue #166

2022-08-18 13:02 UTC, kdreher requested changes

2022-08-18 13:02 UTC, kdreher commented on simpa/utils/processing_device.py
> +def get_processing_device(used_settings: Settings = None) -> torch.device:
the argument is called "global_settings" in the docstring. Please rename it consistently to `global_settings`

2022-08-18 13:02 UTC, kdreher commented on simpa/core/simulation_modules/reconstruction_module/reconstruction_utils.py
> +def get_reconstruction_processing_unit(global_settings: Settings) -> torch.device:
I don't think we still need this function when we have the generalized function. Remove it and use the `get_processing_device` function

2022-08-19 10:03 UTC, TomTomRixRix commented
Both comments should be resolved now. Regarding the name of the parameter: It was `global_settings` in the old version of the function, that's why it was still left over in the docstring. However, we thought that the settings do not necessarily need to be `global` but could also be some other settings where the `Tags.USE_GPU` tag is set. That's why we renamed it to `used_settings`. But I'm also fine with just writing `global_settings` as this will most likely be the place where the tag is set 😊

2022-09-09 11:34 UTC, kdreher approved these changes
Looks good

2022-09-09 11:42 UTC, merged