added "in_Hz" in variable names to specify unit globally, since we ac…
IMSY-DKFZ/simpa pull request #200
Opened 2023-01-25 12:12 UTC by cbender98

…tually always used values in Hz (in contrast to the wrong comments of the functions)

debugged unsymmetric window, edge case and rounding of cutoffs in tukey bandpass

added tests for testing edge cases (no filtering, filtering only one frequency)

2023-01-27 15:42 UTC, TomTomRixRix requested changes
I haven't run the code and tested it yet, but just from looking at the diff I've inserted some comments. You might probably also update the PR title and add the current text into the description as the PR is not just about the "in_Hz" addition but mostly about the rfft and window function correction.

2023-02-07 17:45 UTC, cbender98 commented on simpa/core/simulation_modules/reconstruction_module/reconstruction_utils.py
> +    window[small_index:large_index+1] = win
since indexing [:INDEX] does not include the value at INDEX, it should be correct.

2023-02-07 17:49 UTC, cbender98 commented on simpa/core/simulation_modules/reconstruction_module/reconstruction_utils.py
> +    win = tukey(large_index - small_index + 1, alpha=tukey_alpha)
when i tested the edge cases (no filtering at all, exactly one frequency filtering), i came up with this solution:
no filtering at all:
then small index would be zero and large index would be the last index of the array, however the len of the time series data is not just large_index - small_index but large_index - small_index +1. if you want to apply a window with 1s for the whole array it has to be of the same size

flooring the large_index should correspond to neglecting all frequencies above the the given lowpass cutoff (which makes sense for me and what actually was in the comment of the old version but was not correctly implemented, imo)

2023-02-07 17:51 UTC, cbender98 commented on simpa/core/simulation_modules/reconstruction_module/reconstruction_utils.py
> +    # array of frequencies in Hz corrsponding to rfft and irfft method
added this in the description of the function (line 154)

2023-02-07 17:51 UTC, cbender98 commented on simpa/core/simulation_modules/reconstruction_module/reconstruction_utils.py
>      # construct bandpass filter given the cutoff values with tukey window in negative and positive frequencies
updatet this in the latest commit

2023-03-10 10:47 UTC, TomTomRixRix approved these changes
looks good to me

2023-07-27 09:27 UTC, merged