Fix ignored acoustical_simulation_3d
IMSY-DKFZ/simpa pull request #251
Opened 2023-10-01 13:43 UTC by faberno

**Please check the following before creating the pull request (PR):**
- [x] Did you run automatic tests?
- [ ] Did you run manual tests?
- [x] Is the code provided in the PR still backwards compatible to previous SIMPA versions?

 **Provide issue / feature request fixed by this PR**
 
 Fixes #223

For now added a standard check if the Tag is in the settings, if not use False as default. In the future it would be nice to support .get() in Settings.

2023-10-06 13:30 UTC, TomTomRixRix requested changes
I would prefer it to have just one boolean variable to switch between 2D and 3D. Now we have `acoustic_simulation_3d` and `simulate_2d`. While this should technically work, it makes it very complicated to understand, especially with negated conditional statements.

I would do a one liner where you check for the tag and directly access it:
```python
if Tags.ACOUSTIC_SIMULATION_3D in settings and not settings[Tags.ACOUSTIC_SIMULATION_3D]:
    # 2D case
else:
    #3D case
```

2023-10-06 13:30 UTC, TomTomRixRix commented
And here also merge into `develop` first, before merging into `main`

2024-08-13 08:13 UTC, jgroehl requested changes

2024-08-13 08:13 UTC, jgroehl commented on simpa/core/simulation_modules/acoustic_forward_module/acoustic_forward_module_k_wave_adapter.py
> +        if not self.component_settings[Tags.ACOUSTIC_SIMULATION_3D] and \
I'd change this to the same pattern as lines 158-159 to avoid a key error.

2024-08-13 08:16 UTC, jgroehl approved these changes

2024-08-13 08:26 UTC, merged