Update documentation
IMSY-DKFZ/simpa pull request #308
Opened 2024-06-25 14:49 UTC by jnoelke

**Please check the following before creating the pull request (PR):**
- [ ] Did you run automatic tests?
- [ ] Did you run manual tests?
- [x] Is the code provided in the PR still backwards compatible to previous SIMPA versions?
  
 **List any specific code review questions**
  
 **List any special testing requirements**
 
 **Additional context (e.g. papers, documentation, blog posts, ...)**
  Adds to the original pull request #296 
  
 **Provide issue / feature request fixed by this PR**
 
 Fixes #294

2024-06-25 15:07 UTC, kdreher commented
This should probably not be its own PR but rather done everytime something in the documentation changes. One option could be to add a pre-commit hook that automatically builds the documentation

2024-06-26 08:55 UTC, kdreher requested changes

2024-06-26 08:55 UTC, kdreher commented on docs/source/introduction.md
> +You have to a couple of options to define the required path variables.
Typo "to a"

2024-06-27 07:59 UTC, jnoelke commented
As an alternative, it could also be implemented as a github action

2024-06-27 13:39 UTC, kdreher approved these changes
Looks good

2024-06-27 13:48 UTC, merged