T300 benchmarking
IMSY-DKFZ/simpa pull request #313
Opened 2024-06-26 14:09 UTC by frisograce

**Please check the following before creating the pull request (PR):**
- [x] Did you run automatic tests?
- [ ] Did you run manual tests?
- [x] Is the code provided in the PR still backwards compatible to previous SIMPA versions?

 **Provide issue / feature request fixed by this PR**
 
 Fixes #300

2024-06-27 09:29 UTC, kdreher requested changes
I think the most important thing is to create a new documentation page that explains what's going on in detail. Other than that, it looks good :)

2024-06-27 09:29 UTC, kdreher commented on simpa_examples/msot_invision_simulation.py
> +from typing import Union
see above

2024-06-27 09:29 UTC, kdreher commented on simpa_examples/msot_invision_simulation.py
> +    visualise = config.visualise
see above

2024-06-27 09:29 UTC, kdreher commented on simpa_examples/optical_and_acoustic_simulation.py
> +from typing import Union
see above

2024-06-27 09:29 UTC, kdreher commented on simpa_examples/minimal_optical_simulation_uniform_cube.py
> +    visualise = config.visualise
see above

2024-06-27 09:29 UTC, kdreher commented on simpa_examples/optical_and_acoustic_simulation.py
> +    visualise = config.visualise
see above

2024-06-27 12:05 UTC, frisograce commented
The output benchmarking table looks like that. 
![image](https://github.com/IMSY-DKFZ/simpa/assets/155451092/8e36d635-38f1-4628-8583-10c46eba8c78)

2024-06-27 12:27 UTC, frisograce commented on simpa_examples/benchmarking/extract_benchmarking_data.py
> +            elif profile == 'GPU_MEMORY':
elif makes sense, since we are looping over the profiles. Per iteration only one can be true

2024-06-27 12:29 UTC, frisograce commented on simpa_examples/benchmarking/extract_benchmarking_data.py
> +                    else:
the partitioning is the problem here.

2024-06-27 12:32 UTC, frisograce commented on simpa_examples/benchmarking/extract_benchmarking_data.py
> +            benchmarking_file = open(file_name, 'r')
This makes sure that the variable benchmarking_file is not changes and still contains the original file content.

2024-06-27 12:34 UTC, frisograce commented on simpa_examples/benchmarking/extract_benchmarking_data.py
> +            for lwss in lines_with_sp_simulate:
does not apply. Since we are counting the examples and not the loop variable

2024-06-28 13:38 UTC, kdreher requested changes
One final readability change, then we can merge :)

2024-07-29 12:58 UTC, jgroehl commented
- [ ] We need to add documentation how to install the benchmarking dependencies
- [ ] Also add to `.md` file
- [ ] Add documentation: has to be called directly from the benchmarking folder as the root directory

2024-07-29 13:44 UTC, jgroehl approved these changes

2024-07-29 13:45 UTC, kdreher approved these changes

2024-07-29 13:49 UTC, merged